GET http://localhost:9091/api/project/1/milestone

###

GET http://localhost:9091/api/project/1/milestone/13

###

POST http://localhost:9091/api/project/1/milestone
Content-Type: application/json

{
  "milestoneName": "milestoneName",
  "startDate": "2021-11-11 11:00:00",
  "endDate": "2021-11-11 11:00:00"
}

###

DELETE http://localhost:9091/api/project/1/milestone/16

###

PUT http://localhost:9091/api/project/1/milestone/14
Content-Type: application/json

{
  "milestoneName": "수정된 mileStoneName",
  "startDate": "2021-11-11 11:00:00",
  "endDate": "2021-11-11 11:00:00",
  "projectId": 2
}

###