GET http://localhost:9091/api/member/project/1

###

GET http://localhost:9091/api/member/ttt

###

POST http://localhost:9091/api/member/project/2
Content-Type: application/json

{
  "userId": "test_user20",
  "projectId":2
}

###

DELETE http://localhost:9091/api/member/test_user7/project/1

###

PUT http://localhost:8080/api/member/project/1/member/1
Content-Type: application/json

{
  "userId": "test_user6",
  "projectId":2
}

###