GET http://localhost:8080/api/member/project/2

###

GET http://localhost:8080/api/member/test_user8

###

POST http://localhost:8080/api/member/project/2
Content-Type: application/json

{
  "userId": "test_user8",
  "projectId":2
}

###

DELETE http://localhost:8080/api/member/test_user8/project/1

###

PUT http://localhost:8080/api/member/project/1/member/1
Content-Type: application/json

{
  "userId": "test_user6",
  "projectId":2
}

###