GET http://localhost:9091/api/project/1/task

###

GET http://localhost:9091/api/project/2/task/5

###

POST http://localhost:9091/api/project/1/task
Content-Type: application/json

{
  "taskName": "example project",
  "deadLine": "2023-03-19 00:00:00",
  "content": "this is content of this task",
  "projectId": 1,
  "mileStoneId": 1,
  "userId": "userId"
}

###

DELETE http://localhost:9091/api/project/2/task/9

###

PUT http://localhost:9091/api/project/1/task/11
Content-Type: application/json

{
  "taskName": "example project edited",
  "deadLine": "2023-03-19 00:00:00",
  "content": "this is content of this edited task",
  "projectId": 1,
  "milestoneId": 12,
  "userId": "userId"
}

###

